### ISSUE TITLE
Ability to specify a certificate bundle (.pem) for internal CAs

### ISSUE THREAD

**Issue by JohnOmernik** [moshe/elasticsearch_loader#11]
When we are running Elasticsearch behind a LB using our own CA (that is trusted) it would be nice to be able to provide a CA bundle to pass to the URLLib3 module.

**Comment by moshe** [comment]
Check out version 0.2.0 - new SSL support https://pypi.python.org/pypi/elasticsearch-loader/0.2.0

**Comment by JohnOmernik** [comment]
That is working now, I wish I could pass a flag through that allowed me to hide warnings. (I am still getting a SSL subject alt name depreciation warning... my certs don't have subject alt name on them... makes my screen a mess :)
