### ISSUE TITLE
Is "append" to index an option

### ISSUE THREAD

**Issue by JohnOmernik** [moshe/elasticsearch_loader#12]
I am looking through both docs, code, and test usage, and perhaps I am missing something, but it appears the options are A. Index does not exist, and on a single run of elasticsearch_loader, you can load an entire index or B. Index does exist and you specified --delete therefore the existing index will be deleted.  When you try to run elasticsearch loader on an index that already exists, but do not specify --delete, it fails with error: elasticsearch.exceptions.RequestError: TransportError(400, u'index_already_exists_exception')  

Thus, my request, if possible, is "append" to existing index.

**Comment by moshe** [comment]
Sure, this should be the default behaviur, maybe are you passing index-settings-file when you trying to update the existing index?

**Comment by JohnOmernik** [comment]
Ah, I am AM doing that! I didn't know that is what is causing that... perhaps a note in the help screen or readme that states that the index settings only needs to be provided when first creating the index.  

Alternatively, if the index is exists, and --delete is NOT specified, perhaps we ignore the index-settings file and pass a warning to the user that since the index exists the settings are ignored. (or perhaps we grab the current settings and if they don't match what is passed, we fail out, otherwise, just append as is?) Lots of options with different levels of complexity, but thanks for pointing out my base mistake.
