### ISSUE TITLE
Parquet groupings

### ISSUE THREAD

**Issue by JohnOmernik** [moshe/elasticsearch_loader#13]
When doing a directory of Parquet files (an option to do a directory without having to pass each file would be great :) I noticed that the time before the ingest starts gets progressively longer the more files there are. On a smaller machine, it would just fail without any sort of warning or error, nothing would happen. In an effort to trouble shoot this, I started upping the number of files, and found that the machine size mattered (I could do all 18 files on a larger machine (128 GB of ram, 24 core) vs a 32GB of ram 8 core machine.  

Would it be possible to run parquet files in batches as well? So that the required resources would be smaller and serialized. This sorta corresponds to #12 as it would require some sort of "append".

**Comment by JohnOmernik** [comment]
So I did some profiling, on my import that worked, Prior to the import actually happening (basically there were no connections to ES in this time, it apparently was just reading the Parquet files), here are some stats:

One Directory
18 Parquet files
Total Size: 632 MB
Smallest file: 32 MB
Largest File: 40 MB
Avg: 35MB
When watching the Elasticsearch_loader process Memory use reached 36 GB of usage!  

This is why it was failing on my other node (Max Mem 32 GB)

So not sure why reading of Parquet files would cause SO much Memory.  Would it be possible to read them in one at a time, and the close the file/free memory? It Appears to try to open all the data at once prior to loading into ES. 

I am happy to help on this (I see the help wanted tag) however, my programming chops are limited, I will dive in and roll up my sleeves where I can. 

Thanks!

**Comment by moshe** [comment]
The root cause is in the progress bar feature, it reads all the files before the actual load in order to estimate the progress, I will add a flag that disables that feature in the near future (pr is welcome here).
in the meantime you can use bash script to lazy loading the files:
```bash
for file in /you/dir/*; do
    elasticsearch_loader --... $file
done
```

**Comment by JohnOmernik** [comment]
Ya, that flag would be helpful, even with the lazy loading method, much of the time spent is spent in gather file sizes... (based on evaluation) thus, removing this will help memory pressure and speed of loads. I will look at the code, but I don't think I will be able to help much here.
