### ISSUE TITLE
Unable to upload tsv file properly

### ISSUE THREAD

**Issue by radicand** [moshe/elasticsearch_loader#17]
When I try to load in a TSV (exported from Excel as 'Unicode Text), it imports the whole header row as one field key, and then each row as the field value. It doesn't appear to separate fields out by the tab.

**Comment by moshe** [comment]
Hi @radicand.
did you issued with --delimiter='\t' ?
can you please supply example file ?

**Comment by radicand** [comment]
Hi @moshe - I didn't use the `--delimiter='\t' option as I didn't see it documented. I'll close this issue and re-open if I have trouble with this the next time I give it a shot. Thanks for the tip!
