### ISSUE TITLE
Sample request

### ISSUE THREAD

**Issue by devssh** [moshe/elasticsearch_loader#26]
Any sample on how to load mappings using a file?

**Comment by moshe** [comment]
sure!
you can see it here: https://github.com/moshe/elasticsearch_loader#load-custom-mappings
the json file should be in elasticsearch settings file:
```
{
    "settings" : {
    },
    "mappings" : {
    }
}
```

**Comment by devssh** [comment]
No, I meant the actual settings file! Thanks!
