### ISSUE TITLE
ReadTimeoutError

### ISSUE THREAD

**Issue by lianyi** [moshe/elasticsearch_loader#37]
Any chance to increase the timeout?  Got the following timeout on initial index loading with settings configuration. 

Thanks
  
```
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.3.54.42', port=9200): Read timed out. (read timeout=10)
```

**Comment by moshe** [comment]
@lianyi Added a new flag for ESL, `--timeout` let me know if you still have issues.

**Comment by lianyi** [comment]
Thanks!
