### ISSUE TITLE
Importing numeric data

### ISSUE THREAD

**Issue by cybcon** [moshe/elasticsearch_loader#39]
Hi,
I'm importing my CSV files into elasticsearch to make visualizations in Kibana.
As I recognized, the script will quote every field in the CSV, so the field type is always text.
Is it possible to make a CSV file specific configuration with field to type mappings or can you implement an autodetection of field types of some generic types such as int, float, text, timestamp.
Or, which will also be an alternative, instead of importing the data into elasticsearch, dump the data as json file (for manual changes). The import with command "json" can be done afterwards.

Regards,
cybcon

**Comment by moshe** [comment]
Hey @cybcon 
You can achieve it by defining the field type in the [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html)
Elasticsearch loader supports custom mapping by adding `--index-settings-file`.
An example settings file content:
```
{
    "settings" : {
    },
    "mappings" : {
    "doc": { 
      "properties": { 
        "title":    { "type": "text"  }, 
        "name":     { "type": "text"  }, 
        "age":      { "type": "integer" },  
        "created":  {
          "type":   "date", 
          "format": "strict_date_optional_time||epoch_millis"
        }
      }
    }
  }
}
```

Let me know if it works for you (:

**Comment by cybcon** [comment]
Hey @moshe 
Thank you for the tip, I will check it out and give you some feedback.
Did I understand correctly that the tool will read the index configuration and prepare the CSV according the property types and if there is a new index, I can adjust the property types by define the index-settings-file. So the Tool will correctly interpret int and float from CSV (and if not defined, the default is string)?

**Comment by moshe** [comment]
No, Elasticsearch doing this "cast" for you, so if you defined a certain field as integer and provided a string of integer, elasticsearch will cast the string to int, and index it.

**Comment by moshe** [comment]
@cybcon Any update?

**Comment by siddharthdivi** [comment]
@moshe so I'll have to write my own custom mapping if I want to import data in other types (like int, float etc.) in ElasticSearch? By default all the fields are read as 'strings' is it?
