### ISSUE TITLE
Error: no such option: --index-settings-file

### ISSUE THREAD

**Issue by savioteles** [moshe/elasticsearch_loader#40]
When the command bellow is runned, throws the error: "Error: no such option: --index-settings-file"

`elasticsearch_loader --index incidents --type incident parquet /tmp/part-00000-4078ca87-b779-4960-9b15-e61ca69d2ece-c000.snappy.parquet --index_settings_file /tmp/settings.json`

**Comment by moshe** [comment]
Hey @savioteles,
put the `--index_settings_file /tmp/settings.json` before the command you wish to execute (`parquet` in your case), the idea is that the flags that are related to elasticsearch should be supplied **before** the input command, so the options for the input parsing comes **after** the input command.
Good:
`elasticsearch_loader --index incidents --type incident csv --delimiter ',' file.csv`
Bad (Note: Delimiter **before** csv command):
`elasticsearch_loader --index incidents --type incident --delimiter ',' file.csv csv`

Good:
`elasticsearch_loader --index incidents --type incident csv --delimiter ',' file.csv`
Bad (Note: type **after** csv command):
`elasticsearch_loader --index incidents --delimiter ',' file.csv --type incident csv`

I hope I made myself clear enough, I will add it to the documantation.

**Comment by molinto** [comment]
I'm doing the same thing:
```
elasticsearch_loader --index_settings_file audit_mapping.json --index audits --http-auth elastic:PASSWORD --type audit csv audit.csv
```

Help plz

**Comment by molinto** [comment]
@moshe

**Comment by moshe** [comment]
Replace underscores with dashes index-settings-file

**Comment by molinto** [comment]
Sorry, I'm an idiot
