### ISSUE TITLE
Numeric Data upload using custom mapping file

### ISSUE THREAD

**Issue by siddharthdivi** [moshe/elasticsearch_loader#53]
@moshe I'd like to write my own custom mapping file to upload numeric data with relevant fields for me to visualize in Kibana. Could you possibly show me an example of a mapping file that I'd have to reference with the --index-settings-file so that I can do the same?

**Comment by moshe** [comment]
hey @siddharthdivi,
Take a look at the attached minimal mappings I supplied, the type is `typeNameHere` and the name of the field is `metric`.
More info [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-create-index.html)
```json
{
    "settings": {
        "mappings": {
            "typeNameHere": {
                "properties": {
                    "metric": {
                        "type": "float"
                    }
                }
            }
        }
    }
}
```

Please close the issue if issue is solved

**Comment by moshe** [comment]
Ref #39

**Comment by siddharthdivi** [comment]
@moshe the following is my mapping :

**Comment by siddharthdivi** [comment]
@moshe the following is my mapping : 

{
"settings": {
"mappings": {
"incident": {
"properties": {
"FlightDate" : {"type" : "date"},
"Quarter" : {"type" : "int"},
"Year" : {"type" : "int"}
}
}
}
}
}

I save it in a file called 'index.json', and run the following command : 
elasticsearch_loader --index-settings-file ./index.json --index incident --type incident csv 2017MergedandProcessed.csv

but I get the following error : 
elasticsearch.exceptions.TransportError: TransportError(500, 'not_x_content_exception', 'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes')

I understand that if I were to send the mapping via a CURL request I'd have to do the following, which works : 
curl -XPUT  'localhost:9200/ml_project?pretty' -H 'Content-Type: application/json' -d '
{
"mappings": {
"ml_project": {
"properties": {
"FlightDate" : {"type" : "date"},
"Quarter" : {"type" : "integer"},
"Year" : {"type" : "integer"}
}
}
}
}'

**Comment by moshe** [comment]
@siddharthdivi can you please supply:
1. elasticsearch version (`curl eshost:9200`)
2. python version `python -V`
3. elasticsearch python version `pip show elasticsearch`
4. esl version `pip show elasticsearch_loader`

I suspect your elasticsearch client is old and not sending the `Content-Type` header, the commands above will let me better understand the issue

**Comment by siddharthdivi** [comment]
* Output of ElasticSearch Version obtained by 'curl -XGET localhost:9200'* : 


{
  "name" : "5RfcR_1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "nrIJQuQySXCGtkVNTqyt-w",
  "version" : {
    "number" : "6.6.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "a9861f4",
    "build_date" : "2019-01-24T11:27:09.439740Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

*Python Version* :

Python 3.6.8 :: Anaconda, Inc.

*Output of 'pip show elastisearch'* :

Name: elasticsearch
Version: 6.3.1
Summary: Python client for Elasticsearch
Home-page: https://github.com/elastic/elasticsearch-py
Author: Honza Král, Nick Lang
Author-email: honza.kral@gmail.com, nick@nicklang.com
License: Apache License, Version 2.0
Location: /opt/anaconda/lib/python3.6/site-packages
Requires: urllib3
Required-by: elasticsearch-loader

*Output of 'pip show elasticsearch_loader'* :

Name: elasticsearch-loader
Version: 0.2.19
Summary: A pythonic tool for batch loading data files (json, parquet, csv, tsv) into ElasticSearch
Home-page: https://github.com/Moshe/elasticsearch_loader
Author: Moshe Zada
Author-email: None
License: UNKNOWN
Location: /opt/anaconda/lib/python3.6/site-packages
Requires: elasticsearch, click, click-stream, click-conf
Required-by:

**Comment by moshe** [comment]
Found it!
```
{
    "settings": {
    },
    "mappings": {
        "incident": {
            "properties": {
                "FlightDate" : {"type" : "date"},
                "Quarter" : {"type" : "integer"},
                "Year" : {"type" : "integer"}
            }
        }
    }
}
```
In my previues comments the mapping section was inside the settings, while it should be outside of it.
`elasticsearch_loader  --index-settings-file ./mappings.json --index incident --type incident csv 2017MergedandProcessed.csv` works for me with same ESL, elasticsearch python and ES server.
@siddharthdivi can you check with the new settings json?

**Comment by siddharthdivi** [comment]
@moshe I've tried the same, but the issue still persists. But I'm able to send a CURL request which creates a mapping with the exact same index configurations. The problem is that I'm not able to read mappings from a custom json file, which leads to the above-mentioned error ('Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes')

**Comment by moshe** [comment]
@siddharthdivi I will try to take a closer look in the next days.
in the meanwhile, can you please provide the full stacktrace of the error? (the last 12~ lines of the output)

**Comment by siddharthdivi** [comment]
@moshe The below is the stack trace. Just to be clear, I'm able to create a mapping by explicitly sending a CURL request but not able to read a custom mapping from a json file.

PUT http://localhost:9200/incident [status:500 request:0.005s]
Traceback (most recent call last):
  File "/opt/anaconda/bin/elasticsearch_loader", line 11, in <module>
    load_entry_point('elasticsearch-loader==0.2.19', 'console_scripts', 'elasticsearch_loader')()
  File "/opt/anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/opt/anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/elasticsearch_loader/__init__.py", line 102, in cli
    ctx.obj['es_conn'].indices.create(index=opts['index'], body=opts['index_settings_file'].read())
  File "/opt/anaconda/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 88, in create
    params=params, body=body)
  File "/opt/anaconda/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore,timeout=timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/anaconda/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, 'not_x_content_exception', 'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes')

**Comment by moshe** [comment]
@siddharthdivi I suspect that there is an issue in the mapping file. I think that ES unable to parse it as json, I've added json load in the latest version (`0.2.24`) of ESL in order to check it. can you upgrade ESL and let me know if you get different error?

**Comment by siddharthdivi** [comment]
@moshe The fix works. Thank you!!
