### ISSUE TITLE
No support for Elasticsearch 5.0.0 GA

### ISSUE THREAD

**Issue by erezkoren** [Moshe/elasticsearch_loader#6]
No support for Elasticsearch 5.0.0 GA, see error below

"Uploading  [###################################-]   98%  00:00:052016-10-31 00:09:51.475786 WARN Chunk 101 got exception (TransportError(400, u'illegal_argument_exception', u'request [/_bulk] contains unrecognized parameter: [consistency]')) while processing"

**Comment by Moshe** [comment]
Issue fixed, let me know if you get the error again.
