### ISSUE TITLE
Specific Keys of Json 

### ISSUE THREAD

**Issue by Indu-sharma** [moshe/elasticsearch_loader#67]
I'd wish to load only specific keys of json file to ES. Would it be able to support ?
Example: 
json --keys a,b.c,d  [json_files]

**Comment by moshe** [comment]
Hi @Indu-sharma,
I have added `--keys`, you can try it in version  `0.4.0`.
add the flag before the format (`elasticsearch_loader --index indexname --keys key1,key2 json files.json`)
Let me know if it works for you (:

**Comment by moshe** [comment]
ping @Indu-sharma

**Comment by Indu-sharma** [comment]
Sure, Thanks a lot @moshe! 
One more ask, many times our ES document id needs to be the concatenation of two fields. Would that be possible to take care of? Thank you.

**Comment by moshe** [comment]
Yes, but it will wait until the next time I will have some free time.
Feel free to make a pr (:
