### ISSUE TITLE
'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes

### ISSUE THREAD

**Issue by jkimrey** [moshe/elasticsearch_loader#70]
Hi.

I'm trying to use Elasticsearch Head (chrome plugin) to query an existing elasticsearch index.  I'm writing out the results in either CSV or JSON to a file.

I'm then trying to use elasticsearch_loader to load the data into another elasticsearch instance.

Every time I try, however, I get the following error:

_'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'not_x_content_exception', 'reason': 'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes'}}, 'data': '_index'}}_

Is it possible (using elastichsearch_loader) to export from one elasticsearch instance (using something like Elasticsearch Head) and import it into another instance without having to change the format/data on the export?

Thanks

**Comment by moshe** [comment]
The error is probably caused by an old elasticsearch python package, can you try to update it to the latest version? `pip install -U elasticsearch`
And no elasticsearch_loader doesn't support loading data from another cluster

**Comment by cepefernando** [comment]
Having the same issue, and running ``` pip install -U elasticsearch ``` did not work.

**Comment by moshe** [comment]
Can you please paste the output of 'python -V' , 'elasticsearch_loader --version' and 'pip show elasticsearch'

Sent from my iPhone
