### ISSUE TITLE
Indexing latitude and longitude as geo_point

### ISSUE THREAD

**Issue by alexlopespereira** [moshe/elasticsearch_loader#71]
Hi,

Is it possible to index latitude and longitude (from a csv file) as geo_point such as defined here 
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html ?

If you point me some high level instructions, I could try to modify the code.

Thanks.

**Comment by moshe** [comment]
Hey @alexlopespereira 
from the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/geo-point.html#geo-point) I see that you can index geo points as "lat,lon" string as follows:
```json
{
  "text": "Geo-point as a string",
  "location": "41.12,-71.34" 
}
```

So basically you can do it natively with esl without any code change.
