### ISSUE TITLE
Working on windows?

### ISSUE THREAD

**Issue by mclurkles** [moshe/elasticsearch_loader#74]
Hey - does this work on windows? Any tips?

**Comment by moshe** [comment]
It should work, you encountered any specific issue?

**Comment by mclurkles** [comment]
Just tried as per the docs - it is maybe not being found in the path. 

What should i be typing into the cmd prompt?

**Comment by moshe** [comment]
just like the docs, `elasticsearch_loader --help`.
I've just released version `v0.5.1` can you update and run
`python -m elasticsearch_loader --help` ?

**Comment by mclurkles** [comment]
Thanks mate! That solved it.

**Comment by moshe** [comment]
Happy to hear 🙂
