### ISSUE TITLE
Can we skip if a document already exist ? ?

### ISSUE THREAD

**Issue by ikewzer0** [moshe/elasticsearch_loader#78]
i was loading a 128gb file :) it was all going well, almost around 74% done. it failed.. 
as i read, default it does is overwrite.. is there any way i can restart loading data and skip the existing documents ?

**Comment by moshe** [comment]
There is no option for this, which format are you using? You can use `head` or `tail` to filter lines

**Comment by ikewzer0** [comment]
elasticsearch_loader --bulk-size 3000 --index rdns --type dnsrecords json rdns.json --lines

that is the command i used.. 
this is how my json file format looks like.. it is around 128gb.. 
```
{"timestamp":"1573629372","name":"1.10.178.205","hostname":"node-a19.pool-1-10.dynamic.totinternet.net","type":"ptr"}
{"timestamp":"1573636816","name":"1.10.178.206","hostname":"node-a1a.pool-1-10.dynamic.totinternet.net","type":"ptr"}
{"timestamp":"1573647966","name":"1.10.178.207","hostname":"node-a1b.pool-1-10.dynamic.totinternet.net","type":"ptr"}
```

**Comment by ikewzer0** [comment]
this tool was the only one which allowed me to import this formatting :smiley:  .. i tried various other tools.. 
i would like to know if i can resume from the place i got error after skipping the existing records.

**Comment by moshe** [comment]
Try `cat rdns.json| tail -n +1000  | elasticsearch_loader --bulk-size 3000 --index rdns --type dnsrecords json - --lines` For skipping first 1000 lines

**Comment by moshe** [comment]
@ikewzer0 any update?

**Comment by ikewzer0** [comment]
@moshe i deleted it before i saw your solution, i think that should've fixed it though.. gonna run again.. is there anyway i can add a retry for failing ones ? am gonna run the import again

**Comment by moshe** [comment]
Add `--with-retry`
