### ISSUE TITLE
Unicode issues loading from utf-8 csv

### ISSUE THREAD

**Issue by JunkMyFunk** [moshe/elasticsearch_loader#8]
I see 

`WARN Chunk 0 got exception ('ascii' codec can't decode byte 0xc3 in position 1548: ordinal not in range(128)) while processing`

when loading a utf-8 encoded csv file

**Comment by moshe** [comment]
Hi @JunkMyFunk, can you attach example csv?

**Comment by kerneltravel** [comment]
@JunkMyFunk it seem your csv file's content is with Utf8 string in position 1548 ( use vim's goto command to jump to position). 
@moshe any csv file with none-ANSI characters will failed to import. some fix need because of python2.x's encoding way

**Comment by antunesleo** [comment]
Also having the same problem.

**Comment by antunesleo** [comment]
@moshe I’m away on holiday until the 9th of January, so i can't give you the precise information because the project I'm working on are in my work machine. It's python 2.7, 20 days ago when I commented I was using the last version of esl, and the csv has some values with non ascII caracters, very common on portuguese language, for example: João. The problem does not happen in python 3+.
When I come back to work I will provide the precise details!

**Comment by moshe** [comment]
@antunesleo I've fixed the issue, please upgrade your ESL version (0.2.13), LMK if you still have issues.
I really appreciate your help (:

**Comment by antunesleo** [comment]
@moshe Thank you. ESL is a great library, i'm glad to help.

**Comment by lyriccoder** [comment]
Hi, I still have the same issue. 
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

Name: elasticsearch-loader
Version: 0.2.24

String: 139766587,75321,Functional / Open / Open-n-Save-ADFwithUnicodeName / æ–‡ä»¶eggsåUSTreat.exe,162274803,TRT-REL1301N-14,18,2018-07-04 21:44:45.44+03,18,"{""branch"":""master"",""version"":""Treat13.0""}",27446

It's a correct Chinese symbol

Is it possible to ignore such an error?

**Comment by moshe** [comment]
@lyriccoder can you please provide the file itself (or even few lines of it in a closed file), I suspect this is related to the file encoding (you can use https://send.firefox.com/).
I tried to reproduce it with the strings you provided but looks ok for me.
Additionally can you please paste the full stack trace of the error?

**Comment by lyriccoder** [comment]
Well, first of all ,when I open file with the `encoding` parameter it works correct.

with open('1.csv', newline='', encoding='utf8') as csvfile

The file is really large (3GB), it is exported from POSTGRESQL:
\COPY status_history_21 TO '/mnt/data/dumps/bad-encoded/status_history_21.csv' CSV HEADER encoding 'utf-8';

Client encode of PostgreSQL is utf-8 also. I'll try to upload that file, but seems it's impossible

**Comment by moshe** [comment]
@lyriccoder can you check version `0.2.25` https://github.com/moshe/elasticsearch_loader/releases/tag/v0.2.25 I've added new `--encoding` flag to the base command for all input files;
 `elasticsearch_loader --encoding 'utf-8' --index status_history_17 --type _doc --timeout 1000.00 csv C:\Elastic_parse\status_history_17.csv > C:\Elastic_parse\status_history_17.res`
If you still have a problem please open a new issue (:

**Comment by lyriccoder** [comment]
Thank you very much, seems it works (I've checked 3 large files)!

**Comment by moshe** [comment]
happy to hear
