### ISSUE TITLE
Get keys from header row

### ISSUE THREAD

**Issue by thomasjohnkane** [moshe/elasticsearch_loader#81]
Hello! In the case of csv files, can you get the keys from the header row?

My goal is to load a csv file like this:
```
id, first_name, last_name
1, thomas, kane
2, john, do
```

And see something like this loaded:
```
{
        "_index" : "people",
        "_type" : "person",
        "_id" : "IuOkjG8Bny05PI-SGOq0",
        "_score" : 1.0,
        "_source" : {
                "id" : "1",
                "first_name" : "Thomas",
                "last_name" : "Kane"
        }
}
```

Is this possible?

Thank!

**Comment by moshe** [comment]
This is the default behavior👋

**Comment by thomasjohnkane** [comment]
Ok, I was just getting `0,1,2`. I'll look into it further on my side. Thanks for the package. Going to be really helpful!
