### ISSUE TITLE
elasticsearch.exceptions.SSLError

### ISSUE THREAD

**Issue by BBerastegui** [moshe/elasticsearch_loader#83]
Hi!

Even without forcing verifying the certificates (and even with a valid certificate) I'm getting this error when connecting:

```
elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056))
```

Also, even though specifying that the protocol in the `es_host` parameter is `https`, when initializing, the `scheme` parameter in the `es_conn` JSON says `http` (I don't know if this has something to do with it):

```
{'index': '[REDACTED]', 'es_host': ('https://[REDACTED],), 'http_auth': '[REDACTED]', 'bulk_size': 500, 'verify_certs': False, 'use_ssl': True, 'ca_certs': None, 'delete': False, 'update': False, 'progress': False, 'type': '_doc', 'id_field': None, 'as_child': False, 'with_retry': False, 'index_settings_file': None, 'timeout': 10.0, 'encoding': 'utf-8', 'keys': [], 'es_conn': <Elasticsearch([{'host': '[REDACTED]', 'port': [REDACTED], 'use_ssl': True, 'scheme': 'http'}])>}
```

It looks like it is a well known problem with the library that `elasticsearch_loader` is using: https://stackoverflow.com/questions/54454126/set-verify-certs-false-yet-elasticsearch-elasticsearch-throws-ssl-error-for-cert

Cheers!

**Comment by moshe** [comment]
Can you paste here the exact command you are running? including esl and es version?

**Comment by BBerastegui** [comment]
I haven't been able to replicate now... I've tried with the same host and `pip3 install elasticsearch_loader` with no issues now.

I'll reopen this issue if I see it again! Sorry!
