### ISSUE TITLE
Empty string in date field returns error

### ISSUE THREAD

**Issue by stobias123** [moshe/elasticsearch_loader#84]
If I have an empty date in my CSV it causes the upload to crash.

```
failed to parse field [Book_Date] of type [date] in document with id 's97vIHABXxdv5IBd1aOp'
```

Field value
```
'Book_Date': '', 
```

**Comment by moshe** [comment]
esl takes the raw data from CSV and puts it in es. JSON is a better fit for your use case, can you transform your input to a JSON file?
