### ISSUE TITLE
 parquet module not found, please install manually

### ISSUE THREAD

**Issue by liveangel-js** [moshe/elasticsearch_loader#9]
What does that mean?
I saw TODO parquet support in readme.md. Does that mean parquet not supported now?

**Comment by moshe** [comment]
Supported, look at [Installation](https://github.com/moshe/elasticsearch_loader#installation) paragraph:
_In order to add parquet support run pip install elasticsearch-loader[parquet]_

Waiting for your response to close

**Comment by moshe** [comment]
Timedout!
@liveangel-js please reopen if you still think there is a issue
