### ISSUE TITLE
`Click` dependency

### ISSUE THREAD

**Issue by darthf1** [moshe/elasticsearch_loader#99]
Hi!

I wanted to give your loader a try, it looks very promising! 

My current project already uses `click==8.0.1` and I get a dependency conflict which prohibits me from using this loader:
```
The conflict is caused by:
  python 0.1 depends on click==8.0.1
  elasticsearch-loader[parquet] 0.6.0 depends on click==7.0
```

Is it possible to upgrade the `click` dependency to `v8`?

**Comment by moshe** [comment]
Sure, feel free to open a pull request

**Comment by DavidTorresOcana** [comment]
Any progress to solve this?

**Comment by skyberd** [comment]
@moshe - I have a branch for this but the repo isn't allowing me to push to a new branch. Can you give me permissions to do so?
